# Generated by Django 2.0.7 on 2018-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planescape',
            name='app',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
