# Generated by Django 2.0.7 on 2018-12-04 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_planescape_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planescape',
            name='ID1',
            field=models.CharField(max_length=20, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='planescape',
            name='ID2',
            field=models.CharField(max_length=20, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='planescape',
            name='ID_Movil1',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID movil 1'),
        ),
        migrations.AlterField(
            model_name='planescape',
            name='ID_Movil2',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID movil 1'),
        ),
        migrations.AlterField(
            model_name='planescape',
            name='ID_Movil3',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID movil 1'),
        ),
        migrations.AlterField(
            model_name='planescape',
            name='app',
            field=models.CharField(default='PlanDeEscape', max_length=50, verbose_name='Aplicacion destino'),
        ),
        migrations.AlterField(
            model_name='planescape',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 12, 8, 0, 400095), verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='planescape',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Se ha usado?'),
        ),
    ]
